# -*- coding: utf-8 -*-
"""geradorNumerosLoteriaV1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Kz3zf82EKEXJhAzYXJDKNnlvx_BgCQEp
"""

# Programa Loteria 
# Números aleatórios (Megasena/Quina/DuplaSena/Lotofácil)

import random

print("###########################################################")
print("##########   LOTERIA   ####################################")
print("##########   Gerador de números aleatórios   ##############")
print("###########################################################")
print("############ Escolha 1 para MEGASENA #########")
print("############ Escolha 2 para QUINA ############")
print("############ Escolha 3 para DUPLASENA ########")
print("############ Escolha 4 para LOTOFÁCIL ########")
print("############ Escolha 5 para LOTOMANIA ########")
print("###########################################################")
print("###########################################################")
print("")

opcao = int(input("Entre com a opção desejada: "))

while opcao > 5:
  opcao = int(input("Entre com a opção desejada: "))

if opcao == 1:
  print("Escolhido MegaSena...")
  print("Aguarde processamento dos 6 números aleatórios...")
  i=0
  while i<6:
    mega = random.randint(1,60)
    print(f"--> {mega}")
    i = i+1

elif opcao == 2:
   print("Escolhido Quina...")
   print("Aguarde processamento dos 5 números aleatórios...")
   i=0
   while i<5:
     quina = random.randint(1,80)
     print(f"--> {quina}")
     i = i+1

elif opcao == 3:
  print("Escolhido DuplaSena...")
  print("Aguarde processamento dos 6 números aleatórios...")
  i=0
  while i<6:
    dupla = random.randint(1,50)
    print(f"--> {dupla}")
    i = i+1
  
elif opcao == 4:
  print("Escolhido Lotofácil...")
  print("Aguarde processamento dos 15 números aleatórios...")
  i=0
  while i<15:
    lotof = random.randint(1,25)
    print(f"--> {lotof}")
    i = i+1

else:
  print("Escolhido Lotomania...")
  print("Aguarde processamento dos 50 números aleatórios...")
  i=0
  while i<50:
    lotom = random.randint(1,99)
    print(f"--> {lotom}")
    i = i+1